export const avatarImages = (set: string = "adventurer-neutral") => [
  `https://api.dicebear.com/6.x/${set}/svg?seed=Mia`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Annie`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Fluffy`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Milo`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Buddy`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Cookie`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Bubba`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Dusty`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Loki`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Jasper`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Zoe`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Lucky`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Samantha`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Gizmo`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Bandit`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Precious`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Felix`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Pumpkin`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Snuggles`,
  `https://api.dicebear.com/6.x/${set}/svg?seed=Gracie`,
];

export const avatarSets = [
  { label: "Adventurer neutral", value: "adventurer-neutral" },
  { label: "Adventurer", value: "adventurer" },
  { label: "Avataaars", value: "avataaars" },
  { label: "Avataaars neutral", value: "avataaars-neutral" },
  { label: "Big ears", value: "big-ears" },
  { label: "Big ears neutral", value: "big-ears-neutral" },
  { label: "Big smile", value: "big-smile" },
  { label: "Bottts", value: "bottts" },
  { label: "Bottts neutral", value: "bottts-neutral" },
  { label: "Croodles", value: "croodles" },
  { label: "Fun emoji", value: "fun-emoji" },
  { label: "Icons", value: "icons" },
  { label: "Identicon", value: "identicon" },
  { label: "Lorelei", value: "lorelei" },
  { label: "Lorelei neutral", value: "lorelei-neutral" },
  { label: "Micah", value: "micah" },
  { label: "Miniavs", value: "miniavs" },
  { label: "Notionists", value: "notionists" },
  { label: "Notionists neutral", value: "notionists-neutral" },
  { label: "Open peeps", value: "open-peeps" },
  { label: "Pixel art", value: "pixel-art" },
  { label: "Pixel art neutral", value: "pixel-art-neutral" },
  { label: "Shapes", value: "shapes" },
  { label: "Thumbs", value: "thumbs" },
];
